apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "hello.name" . }}-external-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: {{ include "hello.name" . }}-secret  # name of the secret in the store
  data:
  - secretKey: PORT # name of the key in the secret
    remoteRef:
      key: secret/data/app/hello/config
      property: PORT
  - secretKey: VAULT_HELLO_HOST 
    remoteRef:
      key: secret/data/app/hello/config
      property: VAULT_HELLO_HOST
  - secretKey: VAULT_HELLO_PORT 
    remoteRef:
      key: secret/data/app/hello/config
      property: VAULT_HELLO_PORT
